// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYBLVh0a747rNo5NNm1cTUypeej0dgU9Q',
    appId: '1:196711973140:web:050bb112873b29201b0201',
    messagingSenderId: '196711973140',
    projectId: 'libsy-3cba6',
    authDomain: 'libsy-3cba6.firebaseapp.com',
    storageBucket: 'libsy-3cba6.appspot.com',
    measurementId: 'G-XK69X8N8N2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWrU-Bue8dq91cOwwF7A8AX-Wo-TCom2M',
    appId: '1:196711973140:android:066d0a1c75a0b1641b0201',
    messagingSenderId: '196711973140',
    projectId: 'libsy-3cba6',
    storageBucket: 'libsy-3cba6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo5ZnFz36jbjV1y1x4zaxbW1MDrEmgSxw',
    appId: '1:196711973140:ios:1a1219a4b05fdbe91b0201',
    messagingSenderId: '196711973140',
    projectId: 'libsy-3cba6',
    storageBucket: 'libsy-3cba6.appspot.com',
    iosBundleId: 'com.example.libsy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo5ZnFz36jbjV1y1x4zaxbW1MDrEmgSxw',
    appId: '1:196711973140:ios:2f2400bd8e54e1781b0201',
    messagingSenderId: '196711973140',
    projectId: 'libsy-3cba6',
    storageBucket: 'libsy-3cba6.appspot.com',
    iosBundleId: 'com.example.libsy.RunnerTests',
  );
}
